In [2]:
import numpy as np

list_ = [1,2,3,4,5]

array_list = np.array(object = list_)

In [9]:

# answer of 1st question
import numpy as np

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

q1:
    Yes , both are having a difference in datatype.
    code of the datatype is written above.

In [10]:
#Q2:
print(type(list_))

<class 'list'>


In [11]:
print(type(array_list))

<class 'numpy.ndarray'>


In [16]:
#q3:
array_list = np.array(object = list_, dtype = int)

In [ ]:
yes,there is a difference betwee both the variable

In [13]:
type(array_list)

numpy.ndarray

In [17]:
type(list_)

list

In [19]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [21]:
#q4:
np.shape(num_array)

(2, 3)

In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [34]:
num_array.shape

(2, 3)

In [24]:
np.size(num_array)

6

In [31]:
#q5:
arr1=np.random.randint(0,1,(3,3))

In [30]:
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
#q6:
arr2=np.diag([1,1,1,1,1])

In [33]:
arr2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])